# Generated by Django 3.2.2 on 2024-08-19 18:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('auth_register', '0002_auto_20240816_1711'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
