# Generated by Django 3.2.2 on 2024-08-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_register', '0005_auto_20240820_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Инвайт код для врача'),
        ),
    ]
