# Generated by Django 3.2.2 on 2024-08-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_register', '0006_account_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_doctor',
            field=models.BooleanField(default=False, verbose_name='Индикатор врач/пациент'),
        ),
        migrations.AlterField(
            model_name='account',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Инвайт код'),
        ),
    ]
