# Generated by Django 3.2.2 on 2024-08-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctor_account'),
        ('user', '0003_auto_20240820_1431'),
        ('auth_register', '0008_auto_20240820_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='doctor_data',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_data', to='doctor.doctor', verbose_name='Данные врача'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_data',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='user.user', verbose_name='Данные пользователя'),
        ),
    ]
