# Generated by Django 3.2.2 on 2024-08-13 16:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Должность врача')),
                ('description', models.TextField(blank=True, default='Описание должности', null=True)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя врача')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия врача')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество врача')),
                ('time_registration', models.DateTimeField(auto_now_add=True, verbose_name='Время врача')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон врача')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='Электронная почта врача')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pos', to='doctor.position', verbose_name='Должность врача')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
                'ordering': ['-time_registration'],
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['phone_number', 'slug'], name='doctor_doct_phone_n_44f811_idx'),
        ),
    ]
