# Generated by Django 3.2.2 on 2024-08-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='doctor',
            name='doctor_doct_phone_n_44f811_idx',
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['phone_number'], name='doctor_doct_phone_n_a0b7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['name', 'second_name'], name='doctor_doct_name_1d0abb_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['slug'], name='doctor_doct_slug_a17421_idx'),
        ),
    ]
