# Generated by Django 3.2.2 on 2024-08-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20240814_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='account',
        ),
    ]
