# Generated by Django 3.2.2 on 2024-08-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctor_account'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='doctor',
            name='doctor_doct_slug_a17421_idx',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='slug',
        ),
    ]
