# Generated by Django 3.2.2 on 2024-08-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Время начала смены')),
                ('end_at', models.DateTimeField(verbose_name='Время окончания смены')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doc', to='doctor.doctor', verbose_name='График Врача')),
            ],
            options={
                'verbose_name': 'График Врача',
                'verbose_name_plural': 'График Врачей',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField(verbose_name='Время записи')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor.doctor', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Пациент')),
                ('schedule', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='appointments.scheduledoctor', verbose_name='График Врача')),
            ],
            options={
                'verbose_name': 'Запись пациента',
                'verbose_name_plural': 'Записи пациентов',
                'ordering': ['-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Пациент')),
                ('patient_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.patientrecord', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'История болезни и рекомендации',
            },
        ),
        migrations.AddIndex(
            model_name='scheduledoctor',
            index=models.Index(fields=['doctor'], name='appointment_doctor__30c5e0_idx'),
        ),
        migrations.AddIndex(
            model_name='patientrecord',
            index=models.Index(fields=['patient'], name='appointment_patient_d3bcd3_idx'),
        ),
        migrations.AddIndex(
            model_name='patientrecord',
            index=models.Index(fields=['doctor', 'schedule'], name='appointment_doctor__f7ffca_idx'),
        ),
    ]
