# Generated by Django 3.2.2 on 2024-09-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_part', '0011_auto_20240928_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Время начала смены')),
                ('end_at', models.DateTimeField(verbose_name='Время окончания смены')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='user_part.doctorprofile')),
            ],
            options={
                'verbose_name': 'График Врача',
                'verbose_name_plural': 'График Врачей',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='story_patient', to='user_part.doctorprofile', verbose_name='История болезни пациента')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='user_part.userprofile', verbose_name='История болезни пациента')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField(verbose_name='Время записи')),
                ('description', models.TextField(verbose_name='Заметки врача')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='user_part.doctorprofile', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='user_part.userprofile', verbose_name='Пациент')),
                ('schedule', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='records.scheduledoctor')),
            ],
            options={
                'verbose_name': 'Запись пациента',
                'verbose_name_plural': 'Записи пациентов',
                'ordering': ['-appointment_time'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledoctor',
            index=models.Index(fields=['doctor'], name='records_sch_doctor__1542c7_idx'),
        ),
        migrations.AddIndex(
            model_name='patientrecord',
            index=models.Index(fields=['patient'], name='records_pat_patient_2eb223_idx'),
        ),
        migrations.AddIndex(
            model_name='patientrecord',
            index=models.Index(fields=['doctor'], name='records_pat_doctor__47c85a_idx'),
        ),
    ]
