# Generated by Django 3.2.2 on 2024-09-30 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledoctor',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 30), verbose_name='Рабочий день'),
        ),
        migrations.AlterField(
            model_name='scheduledoctor',
            name='end_at',
            field=models.TimeField(verbose_name='Время окончания смены'),
        ),
        migrations.AlterField(
            model_name='scheduledoctor',
            name='start_at',
            field=models.TimeField(verbose_name='Время начала смены'),
        ),
    ]
