# Generated by Django 3.2.2 on 2024-09-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20240930_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientrecord',
            options={'verbose_name': 'Запись пациента', 'verbose_name_plural': 'Записи пациентов'},
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='ScheduleDoctor',
        ),
    ]
