# Generated by Django 3.2.2 on 2024-10-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0014_auto_20241003_1551'),
        ('records', '0003_auto_20240930_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_part.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_part.userprofile')),
            ],
        ),
    ]
