# Generated by Django 3.2.2 on 2024-10-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0014_auto_20241003_1551'),
        ('records', '0004_patientdoctorrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdoctorrelation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='user_part.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='patientdoctorrelation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='user_part.userprofile'),
        ),
    ]
