# Generated by Django 3.2.2 on 2024-10-04 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0015_doctorprofile_patients'),
        ('records', '0005_auto_20241003_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='description_patient',
            field=models.TextField(default=1, verbose_name='заметки пациента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_records', to='user_part.doctorprofile', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_records', to='user_part.userprofile', verbose_name='Пациент'),
        ),
        migrations.AddConstraint(
            model_name='patientdoctorrelation',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor'), name='patient_doctor_unique'),
        ),
    ]
