# Generated by Django 3.2.2 on 2024-10-04 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20241004_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.date(2024, 10, 5)),
        ),
    ]
