# Generated by Django 3.2.2 on 2024-11-11 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_patientrecord_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.date(2024, 11, 12)),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки врача'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='description_patient',
            field=models.TextField(blank=True, null=True, verbose_name='заметки пациента'),
        ),
    ]
