# Generated by Django 3.2.2 on 2024-12-05 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20241111_1711'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='patientrecord',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.date(2024, 12, 6)),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='status',
            field=models.CharField(choices=[('IN', 'В работе'), ('CL', 'Закрыта'), ('SC', 'Записан')], default=('IN', 'В работе'), max_length=20),
        ),
    ]
