# Generated by Django 5.1.4 on 2024-12-10 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20241205_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.date(2024, 12, 11)),
        ),
    ]
