# Generated by Django 3.2.2 on 2024-08-11 11:27

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=100)),
                ('flat_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Адрес пациента',
                'verbose_name_plural': 'Адреса пациентов',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пациента')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия пациента')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата Рождения')),
                ('time_registration', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон пациента')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('status', models.BooleanField(choices=[(False, 'Здоров'), (True, 'Болен')])),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_address', to='user.address', verbose_name='Адрес пациента')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['-time_registration'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='user_user_phone_n_523d33_idx'),
        ),
    ]
