# Generated by Django 3.2.2 on 2024-08-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record', models.TextField(default=None, verbose_name='История болезни пациента')),
                ('comment_doctor', models.CharField(max_length=255, verbose_name='Комментарии к пациенту')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='medical_record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='record', to='user.medicalrecord', verbose_name='История болезни пациента'),
        ),
    ]
