# Generated by Django 3.2.2 on 2024-08-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240811_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='medical_record',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
