# Generated by Django 3.2.2 on 2024-08-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240820_1431'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_user_slug_e3deb8_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
