# Generated by Django 3.2.2 on 2024-08-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240811_1534'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_user_phone_n_523d33_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Электронная почта пациента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='User_address', to='user.address', verbose_name='Адрес пациента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество пациента'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number', 'slug'], name='user_user_phone_n_6b7998_idx'),
        ),
    ]
