# Generated by Django 3.2.2 on 2024-08-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20240821_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='User_address', to='user.address', verbose_name='Адрес пациента'),
        ),
    ]
