# Generated by Django 3.2.2 on 2024-08-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20240811_2010'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_user_phone_n_6b7998_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='user_user_phone_n_523d33_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['slug'], name='user_user_slug_e3deb8_idx'),
        ),
    ]
