# Generated by Django 3.2.2 on 2024-09-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='description',
            field=models.TextField(verbose_name='Заметки врача'),
        ),
        migrations.CreateModel(
            name='PatientStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='story_patient', to='user_part.doctorprofile', verbose_name='История болезни пациента')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='user_part.userprofile', verbose_name='История болезни пациента')),
            ],
        ),
    ]
