# Generated by Django 3.2.2 on 2024-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0003_remove_userprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
