# Generated by Django 3.2.2 on 2024-09-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0007_auto_20240927_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='birthday',
            field=models.DateField(default='2024-09-27', verbose_name='Дата Рождения'),
        ),
    ]
