# Generated by Django 3.2.2 on 2024-09-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0010_auto_20240927_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientstory',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patientstory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='scheduledoctor',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='birthday',
            field=models.DateField(default='2024-09-28', verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default='2024-09-28', verbose_name='Дата Рождения'),
        ),
        migrations.DeleteModel(
            name='PatientRecord',
        ),
        migrations.DeleteModel(
            name='PatientStory',
        ),
        migrations.DeleteModel(
            name='ScheduleDoctor',
        ),
    ]
