# Generated by Django 3.2.2 on 2024-10-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0012_auto_20240930_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='birthday',
            field=models.DateField(default='2024-10-01', verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default='2024-10-01', verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
