# Generated by Django 3.2.2 on 2024-10-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0013_auto_20241001_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='birthday',
            field=models.DateField(default='2024-10-03', verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default='2024-10-03', verbose_name='Дата Рождения'),
        ),
    ]
