# Generated by Django 3.2.2 on 2024-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20241003_1606'),
        ('user_part', '0014_auto_20241003_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='patients',
            field=models.ManyToManyField(related_name='doctors', through='records.PatientDoctorRelation', to='user_part.UserProfile'),
        ),
    ]
