# Generated by Django 3.2.2 on 2024-11-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0016_auto_20241004_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='birthday',
            field=models.DateField(default='2024-11-11', verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default='2024-11-11', verbose_name='Дата Рождения'),
        ),
    ]
