# Generated by Django 3.2.2 on 2024-12-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0019_auto_20241111_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='birthday',
            field=models.DateField(default='2024-12-05', verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default='2024-12-05', verbose_name='Дата Рождения'),
        ),
    ]
