# Generated by Django 3.2.2 on 2024-12-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0021_alter_doctorprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'permissions': [('can_view_profile', 'Может смотреть свой профиль'), ('can_edit_profile', 'Может редактировать свой профиль'), ('can_edit_record_status', 'Может редактировать статус записи'), ('can_answer_to_question', 'Может отвечать на вопросы пользователя'), ('can_view_doctors_rating', 'Может смотреть рейтинг докторов'), ('can_view_records_patient', 'Может смотреть записи')], 'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['created'], 'permissions': [('can_view_profile', 'Может смотреть свой профиль'), ('can_edit_profile', 'Может редактировать свой профиль'), ('can_edit_record', 'Может редактировать запись к врачу'), ('can_ask_question', 'Может задавать вопросы'), ('can_delete_quetstion', 'Может удалять вопросы'), ('can_view_doctor_list', 'Может смотреть список докторов'), ('can_change_rating_doctors', 'Может менять рейтинг докторов'), ('can_create_record', 'Может создавать записи к врачу'), ('can_view_records', 'Может смотреть записи'), ('can_update_records', 'Может менять записи'), ('can_delete_records', 'Может удалять записи')], 'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='birthday',
            field=models.DateField(default='2024-12-12', verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default='2024-12-12', verbose_name='Дата Рождения'),
        ),
    ]
